import Head from 'next/head'
import DynamicIsland from '../components/DynamicIsland'

const index = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
    <DynamicIsland />
  </>
)

export default index
